version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
 
    volumes:
      - .:/var/www/laravel-docker-sample
    ports:
      - "9000:9000"

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: YOUR MYSQL USER
      MYSQL_PASSWORD: "YOUR PASSWORD"
      MYSQL_ROOT_PASSWORD: "YOUR ROOT MYSQL PASSWORD"

    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./:/var/www/laravel-docker-sample
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  db_data: