name: Build & Push to dev ACR

on:
  push:
    branches: ["main"]
  
  # workflow_dispatch:
jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - uses: docker/login-action@v3
        with:
          # login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{secrets.DOCKER_USER_NAME }}
          password: ${{secrets.DOCKER_TOKEN}}

      - run: |
          docker build -f ./Docker/Laravel/Dockerfile -t laravel-docker-sample:latest .
          docker tag laravel-docker-sample:latest titusfrezer/laravel-docker-sample:latest
          docker push titusfrezer/laravel-docker-sample:latest

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo su
            cd app/Kuraz-online-exam/
            sudo docker compose down
            sudo docker compose up --build -d
            sudo docker ps
